from algo1 import *
from Recursion import *
from LinkedList import *
from Stack import *
n=input_int("Fibonachi Recursiva N°: ")
print(Fibonacci(n))
n=input_int("Sumatorio n-esimo N°: ")
print(Summation(n))
n=input_int("Sumatorio Par n-esimo N°: ")
print(Sum_Even(n))
n=input_int("Fibonachi Stack N°: ")
print(Fibonacci_Stack(n))
print('Lista')
L = LinkedList()
add(L, 2)
add(L, 5)
add(L, 8)
add(L, 1)
add(L, 4)
add(L, 7)
add(L, 3)
add(L, 6)
add(L, 9)
print_L(L)
print()
print('Lista Ordenada')
Organize(L)
print()
print_L(L)
